### PR TITLE
Add setuptools

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@beckermr I don't know if it has been reported yet (could not find it) but it seems like the bot is not happy when using `recipe.yaml` while it contains all the `python_min` statements.

**Comment by beckermr** [comment]
@hadim please open an issue on conda-smithy. this issue appears to be new. thanks for the report!

**Comment by hadim** [comment]
xref https://github.com/conda-forge/conda-smithy/issues/2183

**Comment by beckermr** [comment]
@conda-forge-admin relint

**Pull request merged**
